export const LIVEJOURNAL_ERROR_CODES: { [key: number]: string; } = {
    0: "Unknown Error Code",
    100: "Invalid username",
    101: "Invalid password",
    102: "Can't use custom/private security in communities",
    103: "Poll error",
    104: "Error adding one or more friends",
    105: "Challenge expired",
    150: "Can't post as non-user",
    151: "Banned from journal",
    152: "Can't post back-dated entries in a non-personal journal (??)",
    153: "Incorrect time value",
    154: "Can't add a redirected account as a friend",
    155: "Non-validated email address",
    156: "Protocol authentication denied due to user's failure to accept TOS.",
    157: "Tags error",
    200: "Missing required argument(s)",
    201: "Unknown method",
    202: "Too many arguments",
    203: "Invalid argument(s)",
    204: "Invalid metadata datatype",
    205: "Unknown metadata",
    206: "Invalid destination journal username",
    207: "Protocol version mismatch",
    208: "Invalid text encoding",
    209: "Parameter out of range",
    210: "Client tried to edit with corrupt data. Preventing",
    211: "Invalid or malformed tag list",
    212: "Message body is too long",
    213: "Message body is empty",
    214: "Message looks like spam",
    300: "Don't have access to requested journal",
    301: "Access of restricted feature",
    302: "Can't edit post from requested journal",
    303: "Can't edit post in this community",
    304: "Can't delete post in this community",
    305: "Action forbidden; account is suspended",
    306: "This journal is temporarily in read-only mode. Try again in a couple minutes",
    307: "Selected journal no longer exists",
    308: "Account is locked and cannot be used",
    309: "Account is marked as a memorial (journal is locked and does not accept comments)",
    310: "Account user needs to be age-verified before use",
    311: "Access temporarily disabled",
    312: "Not allowed to add tags to entries in this journal",
    313: "Must use existing tags for entries in this journal (can't create new ones)",
    314: "Only paid users are allowed to use this request",
    315: "User messaging is currently disabled",
    316: "Poster is read-only and cannot post entries",
    317: "Journal is read-only and entries cannot be posted to it",
    318: "Poster is read-only and cannot edit entries",
    319: "Journal is read-only and its entries cannot be edited",
    320: "Sorry, there was a problem with entry content",
    321: "Sorry, deleting is temporary disabled. Entry is 'private' now",
    402: "Your IP address has been temporarily banned for exceeding the login failure rate",
    404: "Cannot post",
    405: "Post frequency limit",
    406: "Client is making repeated requests. Perhaps it's broken?",
    407: "Moderation queue full",
    408: "Maximum queued posts for this <community+poster> combination reached",
    409: "Post is too large",
    410: "Your trial account has expired. Posting is now disabled",
    411: "Action frequency limit",
    500: "Internal server error",
    501: "Database error",
    502: "Database is temporarily unavailable",
    503: "Error obtaining necessary database lock",
    504: "Protocol mode no longer supported",
    505: "Account data format on server is old and needs to be upgraded",
    506: "Journal sync is temporarily unavailable",
};


export class LiveJournalApiError extends Error {
    public constructor(message: string = "Unknown LiveJournal API Error", public readonly code: number = 0) {
        super(`LiveJournal API Error ${code}: ${message}; ${LIVEJOURNAL_ERROR_CODES[code]}`);
    }
}
